### ISSUE TITLE
Allow comments in the blog for non-tekkies

### ISSUE THREAD

**Issue by haimivan** [olieidel/olieidel.github.io#5]
Hi,

I just read parts of [Regulation Is Killing Medical Software Innovation](https://www.eidel.io/2020/08/27/regulation-killing-medical-software-innovation/ ) and thought it might be nice to allow (non-tech) readers to comment directly at the blog post and not here :-)

Apart from that: some snippet thoughts on the subject:

1. further literature on the topic might be 
    Gerd Gigerenzer: `Risiko: Wie man die richtigen Entscheidungen trifft` (and the distinction between risk and uncertainty). And if I remember it right, you might be able to control risk with regulations, but seldom uncertainty.

    Nice detail from the book: the recommendation for hospitals to introduce `check lists` (you do have that in aviation already :-)  )
2. another regulated industry that comes to my mind is: finance / banking. 
3. a certain percentage of people are `bad` and are just looking for easy profits. Does regulation hinder them to just follow their instincts? And sometimes even groups of people do like to do profitable things and only fines might stop them (Volkswagen and the Diesel cars fraud).
4. do big companies foster on purpose the introduction of regulations to keep small startups out of the market?

5. Are un(der)developed countries a better place for two-person startups to try out "new things"? At least regulation is not so dominant there. Or are there other cultures that are more open to innovation than Germany and what would it mean to the regulated economies of Germany / EU in the long term if other economies do have less regulations?

6. sometimes, for deadly ill (cancer) patients there is the practice to "try out" new (not yet clinically tested) drugs - so to say as an act of grace. So sometimes society has ways for innovation - maybe (like with airplane desasters) it just has to be really emotional to change something.
 
7. introducing rules / regulations AND talking to the loud speaking colleague might help to make him clear that he is not only annoying somebody but also breaking a rule. Additionally, you safe yourself effort to have this dialogue whenever a new colleagues comes in the team.

**Comment by olieidel** [comment]
Hey @haimivan, Thanks for your really thoughtful comment!

I'm aware that it took me almost exactly one year to reply, but that doesn't mean I forgot about it - I actually read it a couple times. And then I procrastinated because there wasn't a trivial way for me to set up commenting on my blog without technical pain. In the past, I used disqus for comments, but that wasn't a good idea.

Maybe an old-school solution to this could be to just allow people to email me their comments and then post them there. Sounds simple, but I don't expect many comments anyway.

Regarding your thoughts on the subject of regulation and risk: Really great thoughts! I think we, as a society, need to have a much more open discussion about this subject. It's easy to increase regulation (and that's what has been happening) but it's hard to see what we're missing out on once everything has become complicated though regulation.
